### ISSUE TITLE
Publish this on datahub

### ISSUE THREAD

**Issue by rufuspollock** [datasets/s-and-p-500-companies-financials#2]
@Mikanebu can we please get this added to core list and published on datahub.

**Comment by Mikanebu** [comment]
FIXED, it is live now https://datahub.io/core/s-and-p-500-companies-financials

**Comment by rufuspollock** [comment]
@Mikanebu is something in place so this regularly updates? If not, can you please open an issue for that ...

**Comment by Mikanebu** [comment]
@rufuspollock It is not, travis.yml is not configured and broken. Created new issue here https://github.com/datasets/s-and-p-companies-financials/issues/3
